global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO
  format: json

accessLog:
  format: json

api:
  dashboard: true
  insecure: false

ping:
  entryPoint: admin

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  admin:
    address: ":8081"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
